const gulp = require("gulp");
const webpack = require("webpack");

const tasks = require("./tasks/gulptasks.js");
const browserSync = require("browser-sync").create();

const webpackConfig =
    process.env.NODE_ENV === "production" ? "./webpack.config.prod.js" : "./webpack.config.js";

// run webpack to compile the script into a bundle
function compile(done) {
    return new Promise((resolve, reject) => {
        webpack(require(webpackConfig), (err, stats) => {
            if (err) {
                return reject(err);
            }

            if (stats.hasErrors()) {
                return reject(new Error(stats));
            }
            resolve();
        });
    });
}

function serve(done) {
    browserSync.init(
        {
            server: "./build",
            port: 8080,
            host: "0.0.0.0"
        },
        done
    );
}

function watch(done) {
    return gulp.watch(
        "**/*", // watch everything...
        {
            ignored: [
                // ...except for things generated by the build process.
                "build/**/*"
            ]
        },
        // when something changes, rebuild + reload
        gulp.series(
            tasks.clean,
            tasks.copyAssets,
            tasks.copyHtml,
            tasks.copyCss,
            tasks.copyJs,
            tasks.copyManifest,
            compile,
            reload
        )
    );
}

function reload(done) {
    browserSync.reload();
    done();
}

gulp.task("copy:html", tasks.copyHtml);
gulp.task("copy:css", tasks.copyCss);
gulp.task("copy:assets", tasks.copyAssets);
gulp.task("copy:js", tasks.copyJs);
gulp.task("copy:manifest", tasks.copyManifest);
gulp.task(
    "server",
    gulp.series(
        tasks.clean,
        tasks.copyAssets,
        tasks.copyHtml,
        tasks.copyCss,
        tasks.copyJs,
        tasks.copyManifest,
        compile,
        serve,
        watch
    )
);

gulp.task(
    "auto",
    gulp.series(
        tasks.clean,
        tasks.copyAssets,
        tasks.copyHtml,
        tasks.copyCss,
        tasks.copyJs,
        tasks.copyManifest,
        compile,
        watch
    )
);

// default includes all
gulp.task(
    "default",
    gulp.series(
        tasks.clean,
        tasks.copyAssets,
        tasks.copyHtml,
        tasks.copyCss,
        tasks.copyJs,
        tasks.copyManifest,
        compile
    )
);
